### PR TITLE
refactor: Track rebase of our work onto cosmos-sdk v0.45.0

### PR DESCRIPTION
**Pull request by sunnya97**
## Description

Tracking rebase process of cherry picking our commits on top of upstream/v0.45.0

Part of https://github.com/osmosis-labs/osmosis/issues/770

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed 
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by sunnya97** [comment]
We probably want to cherry-pick

https://github.com/cosmos/cosmos-sdk/pull/10990

**Comment by sunnya97** [comment]
We probably want to cherry-pick https://github.com/cosmos/cosmos-sdk/pull/10990

Should we "re-rebase" onto 0.45.1 once its released, or just cherry-pick the commit?

@ValarDragon

**Comment by ValarDragon** [comment]
just the commit imo. Theres several such open PRs in the SDK to 45, and I don't think we should wait on them.

**Comment by sunnya97** [comment]
Squashed a bunch of commits that were part of the same feature/issue

**Comment by sunnya97** [comment]
@ValarDragon I shouldn't worry about the test-race (02) test failing, right?

**Comment by sunnya97** [comment]
TODO: Figure out which of this stuff we can upstream to mainline cosmos sdk

**Comment by ValarDragon** [comment]
yeah test-race failing is not an issue

**Comment by sunnya97** [comment]
What should I rename this branch to?

**Comment by ethanfrey** [comment]
Awesome to see this progress.
And https://github.com/osmosis-labs/osmosis/pull/782

I'm ready to finalise https://github.com/osmosis-labs/osmosis/pull/769 once these are both merged (we tagged wasmd 0.22 yesterday with cosmos-sdk 0.45 support)

**Comment by ValarDragon** [comment]
Looks like 3575fe587d085862e07fb39bd3e4f01ceca2d04c ( MustUpdateValidatorCommission ) was dropped?

**Comment by ValarDragon** [comment]
Note to self: https://github.com/osmosis-labs/cosmos-sdk/commit/dad6e874dc5e7121ee73af836bdceb7d1054f6c1 is not included, need to configure the IAVL cache size param / config default prior to next release.

**Comment by ValarDragon** [comment]
This LGTM! I think we just need to cherry-pick back in 3575fe587d085862e07fb39bd3e4f01ceca2d04c

EDIT: I'm wrong, its in there somewhere.

Making a new branch off of this called v0.45.0x-osmo-v7, and setting as default

Thanks for doing this!

**Pull request closed without merging**
