### PR TITLE
fix: Remove genesis supply offsets

### PR DESCRIPTION
**Pull request by nicolaslara**
Needed for https://github.com/osmosis-labs/osmosis/issues/2307

## What is the purpose of the change

The sdk fork is using GenesisSupplyOffsets in the banktypes.NewGenesisState() constructor. This is incompatible with the ibc-go testing package which expects the new signature (https://github.com/cosmos/ibc-go/tree/main/testing).

## Brief Changelog

  - Updated the constructor to match the expected interface. 
  - Added a new constructor that can be used for the previous behaviour

## Testing and Verifying

Tests pass

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (no)
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (no)
  - How is the feature or change documented? (not applicable)

### CODE REVIEW

**Comment by ValarDragon** [comment]
We should change NewGenesisState as done here, and make a new method for `NewGenesisStateWithSupplyOffsets` I think for now.

**Comment by nicolaslara** [comment]
Updated according to @ValarDragon's comments. Less changes this way (even if we keep the legacy GenesisSuplyOffsets around)

**Comment by nicolaslara** [comment]
@alexanderbez I tried merging main into this branch, but had issues with the integrations on the osmosis side. Are the changes from https://github.com/osmosis-labs/cosmos-sdk/commit/a296bdc79450be41666e1d235ffd5ed0269305dd already reflected on osmosis/main?

**Comment by nicolaslara** [comment]
Closing in favor of https://github.com/osmosis-labs/cosmos-sdk/pull/312

**Pull request closed without merging**
