### PR TITLE
chore(deps): unfork IAVL to v0.19.1

### PR DESCRIPTION
**Pull request by p0mvn**
Closes: #XXX

## What is the purpose of the change

Unforking IAVL to https://github.com/cosmos/iavl/releases/tag/v0.19.1

Related to: These changes are already upstreamed: https://github.com/cosmos/cosmos-sdk/pull/12626

## Testing and Verifying

This change is a trivial rework / code cleanup without any test coverage.

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? no
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? no
  - How is the feature or change documented? not applicable

### CODE REVIEW

**Comment by p0mvn** [comment]
ref: https://github.com/osmosis-labs/osmosis/issues/2369

**Comment by p0mvn** [comment]
Closing due to stability concerns

**Comment by tac0turtle** [comment]
> Closing due to stability concerns

what stability concerns? the diff is mainly errors and a few other things. Do we need to revert upstream?

**Comment by p0mvn** [comment]
> > Closing due to stability concerns
> 
> what stability concerns? the diff is mainly errors and a few other things. Do we need to revert upstream?

Sorry for the late reply. Missed the notification. 

I've run an Osmosis node with v0.19.1 cosmos IAVL for over 5 days without issues. However, I did not have telemetry setup to observe RAM and I/O usage.

I'm concerned because there are folks who have reported increased I/O usage with v0.19.1, the absence of which I haven't confirmed yet in Osmosis:
https://discord.com/channels/669268347736686612/680435043570941973/1009356834580217887

Additionally, I've observed data races in tests and some dependency issues. I haven't properly investigated them yet.

We decided to postpone this until after Osmosis v12, once more people try cosmos iavl v0.19.1, and we have the time to investigate the data races + telemetry data.

I know that @faddat is looking to unfork us sooner than that though. I have linked him to this PR

**Pull request closed without merging**
