### PR TITLE
refactor: Track rebase of our work onto cosmos-sdk v0.44.3

### PR DESCRIPTION
**Pull request by sunnya97**
Tracking rebase process of cherry picking our commits on top of upstream/v0.44.3

## Description

closes: #XXXX

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Comment by sunnya97** [comment]
Can't cherry-pick https://github.com/osmosis-labs/cosmos-sdk/commit/ce6f14aaa6a0123252a2159ff5b46e191a46d7ff cause ibc was moved to ibc-go.  Remember to import the ante handler feature into osmosis repo.

**Comment by ValarDragon** [comment]
This LGTM. We just need an issue to re-add #9 and figure out why it killed simulation on the 44 line. Going to prepare the Osmo branch for this.

**Comment by ValarDragon** [comment]
LGTM! 

I'm going to take this branch, rebase onto SDK v0.44.x, rename it, and then make it default.

**Comment by ValarDragon** [comment]
Thanks for doing this! Moved to `v0.44.3x-osmo-v5`

**Pull request closed without merging**
