### PR TITLE
fix: implement Amino serialization for x/authz and x/feegrant

### LINKED ISSUE #1434: Include PR #11224 from cosmos-sdk to fix Ledger/Amino authz signing
Hi,

Would it be possible to include the following PR https://github.com/cosmos/cosmos-sdk/pull/11224 into the next release? This would fix the Ledger/Amino authz MsgGrant signing issues that are currently impacting all Ledger users.

Geo

### PR DESCRIPTION
**Pull request by p0mvn**
Closes: https://github.com/osmosis-labs/osmosis/issues/1434

This change backports Amino serialization fix from the `cosmos/cosmos-sdk` repository to enable x/authz and x/feegrant modules to work on the Ledger devices.

Upon beginning to backport the latest relevant change, I realized that our fork is missing a few other minor commits. As a result, I ended up backporting the following:
- https://github.com/cosmos/cosmos-sdk/pull/11129
   * Summary: fixes a non-determinism bug. We needed this because some method signatures were changed. The change seemed small enough, with no merge conflict so I decided to include it to ease cherry-picking other PRs.
- https://github.com/cosmos/cosmos-sdk/pull/11224
  * First attempt at implementing the desired fix by registering interfaces and types on the global legacy codec. This global legacy codec has use cases for other chains where it broke things due to double-registration. As a result, the next PR was made. 
- https://github.com/cosmos/cosmos-sdk/pull/11680
  * This PR fixes the problem above by registering the types and interfaces on a separate codec that belongs in its own package

### CODE REVIEW

**Comment by mattverse** [comment]
@p0mvn does this PR simply backport https://github.com/cosmos/cosmos-sdk/pull/11680 or does this implementation include new features that I focus on more when I'm reviewing this?

**Comment by p0mvn** [comment]
@mattverse it backports all the PRs listed in the description, including https://github.com/cosmos/cosmos-sdk/pull/11680. No extra logic is added on top of the backports

**Review by alexanderbez — COMMENTED** [review]
This seems to encapsulate more changes than what I recall. But it seems reasonable. There are a few breaking changes introduced here.

**Comment by p0mvn** [comment]
@ValarDragon @alexanderbez @mattverse  what do you think should be the course of action on this? Are there any action items for this to become acceptable for merge?

**Comment by alexanderbez** [comment]
AFAIK, we can merge this, but I dont think we can backport this.

**Review by alexanderbez — APPROVED** [review]

**Pull request merged**
