### PR TITLE
chore: Revert "chore: bump go 1.18; bump Tendermint (#321)"

### PR DESCRIPTION
**Pull request by p0mvn**
This reverts commit 01fda2a5331eead2a139ff2f338d6ad8b902e16b.

Closes: #XXX

## What is the purpose of the change

Reverting tm v0.34.21

## Testing and Verifying

This change is a trivial rework / code cleanup without any test coverage.

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? no
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? no
  - How is the feature or change documented? not applicable

### CODE REVIEW

**Comment by czarcas7ic** [comment]
Are all these go reverts to 1.16 required/desired?

**Comment by czarcas7ic** [comment]
What I mean is, should we decouple the go bump from the tendermint bump?

**Review by ValarDragon — APPROVED** [review]

**Comment by ValarDragon** [comment]
I'm ok reverting everything here personally, all part of the bug surface area

**Review by mattverse — APPROVED** [review]
Same opinion here with reverting go version update together, unless we have a specific reason to keep 1.18

**Comment by alexanderbez** [comment]
Are we reverting this just to tag an SDK version compatible with v12?

These changes are a requirement and a foundation for ABCI++ work to land. It's also a prerequisite for https://github.com/osmosis-labs/cosmos-sdk/pull/324.

**Comment by p0mvn** [comment]
> Are we reverting this just to tag an SDK version compatible with v12?
> 
> These changes are a requirement and a foundation for ABCI++ work to land. It's also a prerequisite for #324.

`osmosis-main` will not have anything reverted so it should be fine for any future work depending on this

**Comment by alexanderbez** [comment]
Ahh derp, my bad! I didn't see the base branch 😆 

ACK

**Pull request merged**
