### PR TITLE
fix(ci): backports to v9

### PR DESCRIPTION
**Pull request by p0mvn**
Closes: #XXX

## What is the purpose of the change

backports to v9 are not working. This is an attempt to fix them.

### CODE REVIEW

**Review by mattverse — COMMENTED** [review]
oh interesting is the claim of the PR that backport v9 wasn't working because it didn't have a whitespace between the two CI jobs in the mergify yml file?

**Review by alexanderbez — COMMENTED** [review]
I don't get it haha. This is just a newline addition....

**Comment by p0mvn** [comment]
I couldn't figure out why that was the only label not working. So I made a guess that it is due to formatting / not being parsed correctly haha.

This was the only visual difference I observed. I also verified label names by character and they seem to match

**Comment by alexanderbez** [comment]
mhh I don't think it would be a new line. Perhaps the label is wrong or maybe doesn't exist?

**Comment by mattverse** [comment]
I don't think it would hurt to try if thats the only difference, Im down to merging this

**Review by mattverse — APPROVED** [review]

**Comment by p0mvn** [comment]
Just spent some time looking into this more.

Mergify has a nice dashboard where we it is possible to check if the configuration is applied correctly: https://dashboard.mergify.com/github/osmosis-labs/repo/cosmos-sdk/

According to that dashboard, the rules were getting picked up without the whitespace change here.

So I moved to my personal fork to debug this further. Then, I noticed that I could not push `v0.45.0x-osmo-v9` branch to my fork remote because there was a clash between the branch name and the tag.

It looks like mergify was getting confused for the same reason.

After deleting the erroneous `v0.45.0x-osmo-v9` tag, the mergify backported the latest PR correctly: https://github.com/osmosis-labs/cosmos-sdk/pull/314

Apologies for this PR that wasn't very useful after all

**Pull request closed without merging**
