### PR TITLE
refactor: Fixes the go race tests

### PR DESCRIPTION
**Pull request by ValarDragon**
We used these iterators with no mutex, back when iterator performance was
one of our main blockers, and this step was thought to be of heavy performance impact.

(It does add a notable delay to iteration steps, but it was later learned
the bulk of the problem was due to IAVL & LevelDB interaction)

Its overdue to have turned this off just for simplicity of tests passing.
We still should update the BTree library and remove the need for this
multiple process terrible hack that exists now, but thats work for the future.
(There is no race condition if you look into the details of whats happening,
the gorace detector is off here!)

## Description

Closes: #XXXX

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed 
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Review by alexanderbez — APPROVED** [review]
LGTM

**Comment by alexanderbez** [comment]
@ValarDragon what's up with the failing tests? Are they related?

**Comment by ValarDragon** [comment]
IDK whats going on with the build failures. test-race (00) seems like a different race condition. CC @p0mvn for that one

**Comment by p0mvn** [comment]
I think this has to do with `-race` tests being slower than regular and, as a result, timing out. The test passes on my local machine without a timeout. So it might just mean that we need to find the right timeout value for the CI host machine.

We can tweak the timeout value here: https://github.com/osmosis-labs/cosmos-sdk/blob/d53f1ddaa69130ef455c5f028d144bd03ec77e9f/baseapp/baseapp_test.go#L144

Feel free to merge this PR, I can find the right value for the timeout in a separate PR

Update: created issue to keep track of this

**Comment by alexanderbez** [comment]
@Mergifyio backport v0.45.0x-osmo-v8

**Pull request merged**
