### PR TITLE
feat: Add proto annotations for amino json

### LINKED ISSUE #400: new proto annotations exist upstream
[This PR](https://github.com/cosmos/cosmos-sdk/pull/13501) added amino annotations for codegen.

If we don't want to take the entire PR, I suggest we at least [add this proto file](https://github.com/cosmos/cosmos-sdk/tree/main/proto/amino)

[this PR in Osmosis](https://github.com/osmosis-labs/osmosis/pull/3782) depends on this issue

### PR DESCRIPTION
**Pull request by mattverse**
Closes: https://github.com/osmosis-labs/cosmos-sdk/issues/400

## What is the purpose of the change
Manually brought changes from https://github.com/cosmos/cosmos-sdk/pull/13501, this could be used to better improve client tooling and proto annotations. Planning to get a PR for Osmosis code base as well once we have merged this

## Brief Changelog
- Add proto annotaitons for amino json

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (yes / no)
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (yes / no)
  - How is the feature or change documented? (not applicable   /   specification (`x/<module>/spec/`)  /  [Osmosis docs repo](https://github.com/osmosis-labs/docs)   /   not documented)

### CODE REVIEW

**Comment by pyramation** [comment]
LGTM!

**Review by p0mvn — APPROVED** [review]
utACK

**Comment by p0mvn** [comment]
Hey @mattverse . Can you please look into conflicts here when you have time?

**Comment by mattverse** [comment]
Merging this once CI is passing

**Comment by pyramation** [comment]
🙌🏻

**Pull request merged**
