### PR TITLE
chore: v50.x up to date

### PR DESCRIPTION
**Pull request by faddat**
# Description

This pull request brings the osmosis cosmos-sdk fork current with changes in the mainline cosmos-sdk.

Since a lot of CI doesn't seem to be working, I've run tests manually, they pass for me :). 

I did:

```
make test
```

We also got some warnings from the dependency checker and since they looked relatively uncool, I upgraded:

* golang to v1.23
* hashicorp/go-getter to v1.7.6

---

## Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title, you can find examples of the prefixes below:
    
* [ ] confirmed `!` in the type prefix if API or client breaking change
* [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#pr-targeting))
* [ ] provided a link to the relevant issue or specification
* [ ] reviewed "Files changed" and left comments if necessary
* [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#testing)
* [ ] added a changelog entry to `CHANGELOG.md`
* [ ] updated the relevant documentation or specification, including comments for [documenting Go code](https://blog.golang.org/godoc)
* [ ] confirmed all CI checks have passed

## Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

Please see [Pull Request Reviewer section in the contributing guide](../CONTRIBUTING.md#reviewer) for more information on how to review a pull request.

I have...

* [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] confirmed all author checklist items have been addressed
* [ ] reviewed state machine logic, API design and naming, documentation is accurate, tests and test coverage

### CODE REVIEW

**Comment by faddat** [comment]
Most of the CI jobs fail because we don't have sonarcloud credentials in github.

Should I remove them?

**Comment by PaddyMc** [comment]
Thanks @faddat, the team rn are all testing v26, so this will probs sit here for about a week and a half, I'll come back to it then :bow: 

I think I'll see if there's a way to run these with sonarcloud from your branch, if not we may have to cannibalise this PR :cry:

**Comment by faddat** [comment]
@PaddyMc - I think that some fixes have been ninjaed into the upstream v0.50.x branch, and probably they should get in v26.  I'd want them if I were you, anyhow :).

I am working with another org right now and we have decided to use this SDK fork -- so if the sonarcloud runs in osmo/v0.50.x but not here, that's totally okay.  I will leave the CI config as it currently is in that case, and import from here.  

That is also the reason for some of the PRs on `osmosis` like 

* https://github.com/osmosis-labs/osmosis/pull/8685

Since I can push to branches in the `osmosis-labs` org then import from the commit, there's no rush on any of this :)

Good luck with the release!

**Comment by PaddyMc** [comment]
Thanks for this PR, but decided to take this on myself so I had a good understanding what is happening :bow:

**Pull request closed without merging**
